"""Fairness check on the i.i.d. DGP (plan Etapa 4c, item 14).

If the HPIN only "finds" persistence when it is truly present, then on data
generated by the *static* PIN DGP (degenerate Gamma, i.e. i.i.d. states) the
estimated transition matrix should collapse to identical rows equal to the
stationary distribution (Gamma ~= 1 u), the spectral gap should approach its
theoretical maximum of 1, and the HPIN- and PIN-implied probabilities should
agree.
"""

import os
import numpy as np
import pandas as pd

from hpin import fit_hpin, stationary_distribution

HERE = os.path.dirname(__file__)
FLUX = os.path.join(HERE, "..", "data", "fluxos", "sinteticos", "fluxos_sinteticos_iid.csv")
PINS_DIR = os.path.join(HERE, "..", "data", "pins", "sinteticos")
OUT = os.path.join(HERE, "..", "results", "tables")
WINDOWS = [60, 90, 120, 150, 180]

U_TRUE = np.array([0.47368421, 0.26315789, 0.26315789])


def main():
    os.makedirs(OUT, exist_ok=True)
    df = pd.read_csv(FLUX, index_col=0)
    fit = fit_hpin(df["buyer"].values.astype(float), df["seller"].values.astype(float))

    G = fit["Gamma"]
    u = stationary_distribution(G)
    row_spread = np.abs(G - G.mean(axis=0, keepdims=True)).max()
    dist_degenerate = np.abs(G - np.tile(u, (3, 1))).max()
    ev = np.sort(np.abs(np.linalg.eigvals(G)))[::-1]
    print("Full-series HPIN on iid DGP:")
    print("  Gamma_hat:\n", np.round(G, 4))
    print("  stationary u_hat:", np.round(u, 4), "| true stationary:", np.round(U_TRUE, 4))
    print(f"  max row spread: {row_spread:.4f} | max |Gamma - 1u|: {dist_degenerate:.4f}")
    print(f"  spectral gap: {1 - ev[1]:.4f} (degenerate/iid limit: 1.0)")
    print(f"  steady_alpha={fit['steady_alpha']:.4f} (true 0.5263) | "
          f"steady_pin={fit['steady_pin']:.4f} | mu={fit['mu']:.0f} "
          f"eps_b={fit['eps_b']:.0f} eps_s={fit['eps_s']:.0f}")

    summary = [dict(scope="full_series", gamma_row_spread=row_spread,
                    dist_degenerate=dist_degenerate, spectral_gap=1 - ev[1],
                    steady_alpha=fit["steady_alpha"], steady_pin=fit["steady_pin"],
                    mu=fit["mu"], eps_b=fit["eps_b"], eps_s=fit["eps_s"])]

    # rolling-window comparison (requires both rolling runs on the iid data)
    for w in WINDOWS:
        f_h = os.path.join(PINS_DIR, f"pin_hmm_{w}_fluxos_sinteticos_iid.csv")
        f_p = os.path.join(PINS_DIR, f"pin_ekop_{w}_fluxos_sinteticos_iid.csv")
        if not (os.path.exists(f_h) and os.path.exists(f_p)):
            continue
        hp = pd.read_csv(f_h, index_col=0)
        pn = pd.read_csv(f_p, index_col=0)
        common = hp.index.intersection(pn.dropna(subset=["pin"]).index)
        d = hp.loc[common, "pin"] - pn.loc[common, "pin"]
        print(f"  w={w}: median HPIN-PIN pin diff = {d.median():+.4f} | "
              f"median HPIN pin = {hp.loc[common, 'pin'].median():.4f} | "
              f"median PIN pin = {pn.loc[common, 'pin'].median():.4f}")
        summary.append(dict(scope=f"rolling_{w}",
                            median_pin_hpin=hp.loc[common, "pin"].median(),
                            median_pin_pin=pn.loc[common, "pin"].median(),
                            median_diff=d.median()))

    pd.DataFrame(summary).to_csv(os.path.join(OUT, "fairness_iid.csv"), index=False)
    print("saved ->", os.path.join(OUT, "fairness_iid.csv"))


if __name__ == "__main__":
    main()
